name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/saral-ledger-ui/package-lock.json
    
    - name: Install frontend dependencies
      run: npm install
      working-directory: frontend/saral-ledger-ui
    
    - name: Build frontend
      run: npm run build
      working-directory: frontend/saral-ledger-ui
    
    - name: Restore backend dependencies
      run: dotnet restore
      working-directory: backend/SaralLedgerAPI
    
    - name: Build backend
      run: dotnet build --no-restore
      working-directory: backend/SaralLedgerAPI